### ISSUE TITLE
feature request: try to integrate viem

### ISSUE THREAD

**Issue by dionysuzx** [d1onys1us/dapp-slaps#11]
viem looks cool: https://viem.sh/

**Comment by jxom** [comment]
Happy to answer questions!

**Comment by jxom** [comment]
FYI: @wagmi/core will port to viem for v1, so likely there will be not much migration work.

**Comment by dionysuzx** [comment]
> FYI: @wagmi/core will port to viem for v1, so likely there will be not much migration work.

Do you know if viem will play nicely with web3modal? Looks like wagmi is a dependency at the moment.

**Comment by dionysuzx** [comment]
> FYI: @wagmi/core will port to viem for v1, so likely there will be not much migration work.

do you have an idea when wagmi/core v1 is anticipated? thanks!
