### ISSUE TITLE
Web3Modal button hangs when deployed to vercel

### ISSUE THREAD

**Issue by shot-codes** [d1onys1us/dapp-slaps#23]
Hey again, I've just tested out deployment on Vercel without any significant modifications outside of styling. The w3m-button just hangs when clicked and doesn't log anything to the console. Seems your deployment works just fine. Any tips :)?

https://sgmnt-dapp-sgmnt.vercel.app/

**Comment by dionysuzx** [comment]
> Hey again, I've just tested out deployment on Vercel without any significant modifications outside of styling. The w3m-button just hangs when clicked and doesn't log anything to the console. Seems your deployment works just fine. Any tips :)?
> 
> https://sgmnt-dapp-sgmnt.vercel.app/

i'm seeing a console.log error `projectId is required to work with explorer api`. did you set the web3modal project ID in the environment variables? is there another project id you are using? happy to take a look if you share the code, too.

**Comment by shot-codes** [comment]
sure thing https://github.com/sgmnt-art/sgmnt-art :) I didn't notice that console error at first, but I do also see it. I have set my web3modal project Id and it works with localhost. Still the same error with vercel deployment however.

**Comment by shot-codes** [comment]
My bad, had a typo in the env variable set in vercel... works just fine. Thanks
